## The chart API version
apiVersion: v1
## The name of the chart. 
name: techtrends
## A single-sentence description of this project
description: Deploy multiple techtrends applications with Helm
## A list of keywords about this project to quickly identify the chart's capabilities.
keywords:
- techtrends
## The chart version, here set to `3.7.0`
version: 1.0.0
## List of maintainers, their names, and method of contact
maintainers:
- name: Michael Obst
